use_visualization: true
use_painted_image: true

capturer:
  show_loss_framerate: false
  show_loss_framerate_interval: 500
  reconnect_wait_interval: 100
  # hikcamera or local_video
  source: "local_video"
  hikcamera:
    # int
    timeout_ms: 500
    # float
    exposure_us: 2000.0
    # float
    framerate: 60
    # float
    gain: 16.9807

    invert_image: false
    software_sync: false
    trigger_mode: false
    fixed_framerate: true
  local_video:
    # 替换为你具体的路径
    location: "/workspaces/alliance/test_videos/pingpong_v3.mp4"
    # double 帧率
    frame_rate: 60
    # bool 是否循环播放
    loop_play: true
    # bool 是否允许跳帧以满足实时性
    allow_skipping: false

identifier:
  # openvino infer
  model_location: "models/yolov8.onnx"
  infer_device: "AUTO"
  input_rows: 800
  input_cols: 800
  score_threshold: 0.5
  nms_threshold: 0.6

visualization:
  framerate: 60
  monitor_host: "127.0.0.1"
  monitor_port: "5000"
  stream_type: "RTP_JPEG"
